name: Delete Older Artifacts

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 23 * * *'

jobs:
  Cleaning:
    runs-on: ubuntu-20.04

    steps:
    - name: Delete Older Workflows
      uses: GitRML/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 3
        keep_minimum_runs: 0

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
